### ISSUE TITLE
Docker container shows 500 error

### ISSUE THREAD

**Issue by sijoxavier89** [microsoft/dotnet-framework-docker#578] opened 2020-05-12 14:05 UTC
## Steps to reproduce the issue
1. Create docker container using visual studio 2019 for a .Net 3.5 ASMX service
2.When running container it shows internal server error
3. Windows image used - mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019

## Output of `docker version`

```
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false

```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 19
 Server Version: 19.03.8
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows 10 Pro Version 1809 (OS Build 17763.1158)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 8GiB
 Name: cloudcontainer
 ID: G4RY:DFQL:4VC5:TH5X:AOIG:QI4P:RGSR:4VHN:6BA4:UK2Q:72C3:KS5V
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 38
  System Time: 2020-05-12T14:04:56.0044298Z
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by MichaelSimons** [comment] 2020-05-13 18:19
@sijoxavier89 - Is this issue different than https://github.com/microsoft/dotnet-framework-docker/issues/580?  Could you include a set of specific steps that can be used to recreate the issue?

**Comment by sijoxavier89** [comment] 2020-05-15 04:03
@MichaelSimons this seems to be same as #589,Please let me know if you need any aditional info

Steps.

1. Create a WCF project using Visual Studio 2017
2. Right Click on the project -> Add -> Container Orchestrator Support -> Docker Compose
3. After Docker file and Dockercompose files are getting created 
5. F5
6. Now try to access the Service in the container either using a sample client or in Browser 
7. In browser it shows - 500 Internal server error

**Comment by MichaelSimons** [comment] 2020-05-15 12:58
Closing as a duplicate of #589

**Closed by MichaelSimons** 2020-05-15 12:58 UTC
Labels: area:dockerfiles, category:aspnet
