### ISSUE TITLE
Build failure with latest image: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

### ISSUE THREAD

**Issue by mjacob-cald** [microsoft/dotnet-framework-docker#522] opened 2020-02-22 01:47 UTC
I am on Windows server 2019 [latest fresh install]
Download the sample app from: 
https://github.com/microsoft/dotnet-framework-docker/tree/master/samples/aspnetmvcapp

Build the app using docker command
docker build --pull -t aspnetmvcapp .

Throws below error during msbuild phase:
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; msbuild /p:Configuration=Release' returned a non-zero code: 1

docker --version
Docker version 19.03.5, build 2ee0c57608

this sample successfully builds on previous version: 4.8-20200114-windowsservercore-ltsc2019

Complete log:

PS C:\aspnetmvcapp> docker build --pull -t aspnetmvcapp .
Sending build context to Docker daemon  2.691MB

Step 1/12 : FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build
4.8: Pulling from dotnet/framework/sdk
65014b3c3121: Already exists
b5405b758079: Already exists
ac56c610af03: Already exists
d8d61c2ababf: Already exists
0ed57babb001: Already exists
c8a0f45b3421: Already exists
75cb34f91825: Already exists
1949a0bb0ffb: Already exists
316fdf3fc0fa: Already exists
42b0925a3e5c: Already exists
c5e384761600: Already exists
f65f633b9854: Already exists
bd885be04626: Already exists
179844769b6b: Already exists
c037183d4738: Already exists
Digest: sha256:0008d5d893924c10ec01b1619a009c57116f9a943fe43ca772af544c75c9a83a
Status: Downloaded newer image for mcr.microsoft.com/dotnet/framework/sdk:4.8
 ---> 99ad7e1e8763
Step 2/12 : WORKDIR /app
 ---> Running in c35fbee6fed8
Removing intermediate container c35fbee6fed8
 ---> bf84c0dbeab7
Step 3/12 : COPY *.sln .
 ---> 2318d1f0dc16
Step 4/12 : COPY aspnetmvcapp/*.csproj ./aspnetmvcapp/
 ---> d3c53a8b8c77
Step 5/12 : COPY aspnetmvcapp/*.config ./aspnetmvcapp/
 ---> c58cad0909d0
Step 6/12 : RUN nuget restore
 ---> Running in bbaf29eac7f1
MSBuild auto-detection: using msbuild version '16.4.0.56107' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin'.
[91m
[0mWARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
Restoring NuGet package Microsoft.ApplicationInsights.Agent.Intercept.2.0.6.
Restoring NuGet package Antlr.3.4.1.9004.
Restoring NuGet package bootstrap.3.4.1.
Restoring NuGet package Microsoft.ApplicationInsights.2.2.0.
Restoring NuGet package jQuery.1.10.2.
Restoring NuGet package jQuery.Validation.1.11.1.
Restoring NuGet package Microsoft.ApplicationInsights.PerfCounterCollector.2.2.0.
Restoring NuGet package Microsoft.ApplicationInsights.DependencyCollector.2.2.0.
Restoring NuGet package Microsoft.ApplicationInsights.Web.2.2.0.
Restoring NuGet package Microsoft.ApplicationInsights.WindowsServer.2.2.0.
Restoring NuGet package Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.2.0.
Restoring NuGet package Microsoft.AspNet.Mvc.5.2.3.
Restoring NuGet package Microsoft.AspNet.Razor.3.2.3.
Restoring NuGet package Microsoft.AspNet.Web.Optimization.1.1.3.
Restoring NuGet package Microsoft.AspNet.WebApi.5.2.3.
Restoring NuGet package Microsoft.AspNet.WebApi.Client.5.2.3.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.agent.intercept/2.0.6/microsoft.applicationinsights.agent.intercept.2.0.6.nupkg
  GET https://api.nuget.org/v3-flatcontainer/antlr/3.4.1.9004/antlr.3.4.1.9004.nupkg
  GET https://api.nuget.org/v3-flatcontainer/jquery.validation/1.11.1/jquery.validation.1.11.1.nupkg
  GET https://api.nuget.org/v3-flatcontainer/bootstrap/3.4.1/bootstrap.3.4.1.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights/2.2.0/microsoft.applicationinsights.2.2.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/jquery/1.10.2/jquery.1.10.2.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.dependencycollector/2.2.0/microsoft.applicationinsights.dependencycollector.2.2.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.perfcountercollector/2.2.0/microsoft.applicationinsights.perfcountercollector.2.2.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.windowsserver.telemetrychannel/2.2.0/microsoft.applicationinsights.windowsserver.telemetrychannel.2.2.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.web/2.2.0/microsoft.applicationinsights.web.2.2.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.windowsserver/2.2.0/microsoft.applicationinsights.windowsserver.2.2.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.mvc/5.2.3/microsoft.aspnet.mvc.5.2.3.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.razor/3.2.3/microsoft.aspnet.razor.3.2.3.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.web.optimization/1.1.3/microsoft.aspnet.web.optimization.1.1.3.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.webapi/5.2.3/microsoft.aspnet.webapi.5.2.3.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.webapi.client/5.2.3/microsoft.aspnet.webapi.client.5.2.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/jquery.validation/1.11.1/jquery.validation.1.11.1.nupkg 22ms
Installing jQuery.Validation 1.11.1.
  OK https://api.nuget.org/v3-flatcontainer/antlr/3.4.1.9004/antlr.3.4.1.9004.nupkg 71ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.agent.intercept/2.0.6/microsoft.applicationinsights.agent.intercept.2.0.6.nupkg 72ms
Installing Antlr 3.4.1.9004.
Installing Microsoft.ApplicationInsights.Agent.Intercept 2.0.6.
  OK https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights/2.2.0/microsoft.applicationinsights.2.2.0.nupkg 77ms
Installing Microsoft.ApplicationInsights 2.2.0.
Adding package 'jQuery.Validation.1.11.1' to folder 'C:\app\packages'
  OK https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.dependencycollector/2.2.0/microsoft.applicationinsights.dependencycollector.2.2.0.nupkg 82ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.mvc/5.2.3/microsoft.aspnet.mvc.5.2.3.nupkg 81ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.webapi/5.2.3/microsoft.aspnet.webapi.5.2.3.nupkg 83ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.razor/3.2.3/microsoft.aspnet.razor.3.2.3.nupkg 84ms
Installing Microsoft.ApplicationInsights.DependencyCollector 2.2.0.
Installing Microsoft.AspNet.Mvc 5.2.3.
Installing Microsoft.AspNet.WebApi 5.2.3.
Installing Microsoft.AspNet.Razor 3.2.3.
  OK https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.windowsserver.telemetrychannel/2.2.0/microsoft.applicationinsights.windowsserver.telemetrychannel.2.2.0.nupkg 88ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.web/2.2.0/microsoft.applicationinsights.web.2.2.0.nupkg 89ms
Installing Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 2.2.0.
Installing Microsoft.ApplicationInsights.Web 2.2.0.
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.webapi.client/5.2.3/microsoft.aspnet.webapi.client.5.2.3.nupkg 90ms
  OK https://api.nuget.org/v3-flatcontainer/jquery/1.10.2/jquery.1.10.2.nupkg 95ms
Installing Microsoft.AspNet.WebApi.Client 5.2.3.
Installing jQuery 1.10.2.
Adding package 'Microsoft.AspNet.WebApi.5.2.3' to folder 'C:\app\packages'
  OK https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.perfcountercollector/2.2.0/microsoft.applicationinsights.perfcountercollector.2.2.0.nupkg 106ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.applicationinsights.windowsserver/2.2.0/microsoft.applicationinsights.windowsserver.2.2.0.nupkg 106ms
Installing Microsoft.ApplicationInsights.PerfCounterCollector 2.2.0.
Installing Microsoft.ApplicationInsights.WindowsServer 2.2.0.
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.web.optimization/1.1.3/microsoft.aspnet.web.optimization.1.1.3.nupkg 110ms
Installing Microsoft.AspNet.Web.Optimization 1.1.3.
Added package 'Microsoft.AspNet.WebApi.5.2.3' to folder 'C:\app\packages'
Restoring NuGet package Microsoft.AspNet.WebApi.Core.5.2.3.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.webapi.core/5.2.3/microsoft.aspnet.webapi.core.5.2.3.nupkg
Added package 'jQuery.Validation.1.11.1' to folder 'C:\app\packages'
Restoring NuGet package Microsoft.AspNet.WebApi.WebHost.5.2.3.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.webapi.webhost/5.2.3/microsoft.aspnet.webapi.webhost.5.2.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/bootstrap/3.4.1/bootstrap.3.4.1.nupkg 147ms
Installing bootstrap 3.4.1.
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.webapi.webhost/5.2.3/microsoft.aspnet.webapi.webhost.5.2.3.nupkg 23ms
Installing Microsoft.AspNet.WebApi.WebHost 5.2.3.
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.webapi.core/5.2.3/microsoft.aspnet.webapi.core.5.2.3.nupkg 42ms
Installing Microsoft.AspNet.WebApi.Core 5.2.3.
Adding package 'Microsoft.AspNet.Web.Optimization.1.1.3' to folder 'C:\app\packages'
Added package 'Microsoft.AspNet.Web.Optimization.1.1.3' to folder 'C:\app\packages'
Restoring NuGet package Microsoft.AspNet.WebPages.3.2.3.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.webpages/3.2.3/microsoft.aspnet.webpages.3.2.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.webpages/3.2.3/microsoft.aspnet.webpages.3.2.3.nupkg 37ms
Installing Microsoft.AspNet.WebPages 3.2.3.
Adding package 'Antlr.3.4.1.9004' to folder 'C:\app\packages'
Adding package 'Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.2.0' to folder 'C:\app\packages'
Adding package 'Microsoft.AspNet.WebApi.WebHost.5.2.3' to folder 'C:\app\packages'
Adding package 'Microsoft.ApplicationInsights.WindowsServer.2.2.0' to folder 'C:\app\packages'
Adding package 'Microsoft.AspNet.Razor.3.2.3' to folder 'C:\app\packages'
Adding package 'Microsoft.ApplicationInsights.DependencyCollector.2.2.0' to folder 'C:\app\packages'
Adding package 'Microsoft.AspNet.Mvc.5.2.3' to folder 'C:\app\packages'
Adding package 'Microsoft.ApplicationInsights.PerfCounterCollector.2.2.0' to folder 'C:\app\packages'
Adding package 'Microsoft.ApplicationInsights.Web.2.2.0' to folder 'C:\app\packages'
Adding package 'jQuery.1.10.2' to folder 'C:\app\packages'
Added package 'Microsoft.AspNet.WebApi.WebHost.5.2.3' to folder 'C:\app\packages'
Restoring NuGet package Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.codedom.providers.dotnetcompilerplatform/1.0.8/microsoft.codedom.providers.dotnetcompilerplatform.1.0.8.nupkg
Added package 'Antlr.3.4.1.9004' to folder 'C:\app\packages'
Restoring NuGet package Microsoft.jQuery.Unobtrusive.Validation.3.2.3.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.jquery.unobtrusive.validation/3.2.3/microsoft.jquery.unobtrusive.validation.3.2.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.codedom.providers.dotnetcompilerplatform/1.0.8/microsoft.codedom.providers.dotnetcompilerplatform.1.0.8.nupkg 16ms
Installing Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.8.
Adding package 'Microsoft.AspNet.WebApi.Core.5.2.3' to folder 'C:\app\packages'
Added package 'Microsoft.AspNet.Razor.3.2.3' to folder 'C:\app\packages'
Restoring NuGet package Microsoft.Net.Compilers.2.4.0.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.net.compilers/2.4.0/microsoft.net.compilers.2.4.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.jquery.unobtrusive.validation/3.2.3/microsoft.jquery.unobtrusive.validation.3.2.3.nupkg 37ms
Installing Microsoft.jQuery.Unobtrusive.Validation 3.2.3.
  OK https://api.nuget.org/v3-flatcontainer/microsoft.net.compilers/2.4.0/microsoft.net.compilers.2.4.0.nupkg 18ms
Installing Microsoft.Net.Compilers 2.4.0.
Added package 'Microsoft.ApplicationInsights.DependencyCollector.2.2.0' to folder 'C:\app\packages'
Restoring NuGet package Microsoft.Web.Infrastructure.1.0.0.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.web.infrastructure/1.0.0/microsoft.web.infrastructure.1.0.0.nupkg
Added package 'Microsoft.ApplicationInsights.PerfCounterCollector.2.2.0' to folder 'C:\app\packages'
Restoring NuGet package Modernizr.2.6.2.
  GET https://api.nuget.org/v3-flatcontainer/modernizr/2.6.2/modernizr.2.6.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.web.infrastructure/1.0.0/microsoft.web.infrastructure.1.0.0.nupkg 24ms
Added package 'Microsoft.AspNet.Mvc.5.2.3' to folder 'C:\app\packages'
Installing Microsoft.Web.Infrastructure 1.0.0.0.
Restoring NuGet package Newtonsoft.Json.6.0.4.
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/6.0.4/newtonsoft.json.6.0.4.nupkg
  OK https://api.nuget.org/v3-flatcontainer/modernizr/2.6.2/modernizr.2.6.2.nupkg 17ms
Installing Modernizr 2.6.2.
Added package 'Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.2.0' to folder 'C:\app\packages'
Restoring NuGet package Respond.1.2.0.
  GET https://api.nuget.org/v3-flatcontainer/respond/1.2.0/respond.1.2.0.nupkg
Adding package 'Microsoft.AspNet.WebApi.Client.5.2.3' to folder 'C:\app\packages'
  OK https://api.nuget.org/v3-flatcontainer/respond/1.2.0/respond.1.2.0.nupkg 14ms
Installing Respond 1.2.0.
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/6.0.4/newtonsoft.json.6.0.4.nupkg 41ms
Installing Newtonsoft.Json 6.0.4.
Added package 'Microsoft.AspNet.WebApi.Core.5.2.3' to folder 'C:\app\packages'
Restoring NuGet package WebGrease.1.5.2.
  GET https://api.nuget.org/v3-flatcontainer/webgrease/1.5.2/webgrease.1.5.2.nupkg
Added package 'jQuery.1.10.2' to folder 'C:\app\packages'
Added package 'Microsoft.ApplicationInsights.WindowsServer.2.2.0' to folder 'C:\app\packages'
  OK https://api.nuget.org/v3-flatcontainer/webgrease/1.5.2/webgrease.1.5.2.nupkg 26ms
Installing WebGrease 1.5.2.
Adding package 'Microsoft.Web.Infrastructure.1.0.0' to folder 'C:\app\packages'
Adding package 'Microsoft.jQuery.Unobtrusive.Validation.3.2.3' to folder 'C:\app\packages'
Added package 'Microsoft.AspNet.WebApi.Client.5.2.3' to folder 'C:\app\packages'
Added package 'Microsoft.ApplicationInsights.Web.2.2.0' to folder 'C:\app\packages'
Adding package 'Modernizr.2.6.2' to folder 'C:\app\packages'
Adding package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8' to folder 'C:\app\packages'
Added package 'Microsoft.Web.Infrastructure.1.0.0' to folder 'C:\app\packages'
Adding package 'Microsoft.AspNet.WebPages.3.2.3' to folder 'C:\app\packages'
Added package 'Microsoft.jQuery.Unobtrusive.Validation.3.2.3' to folder 'C:\app\packages'
Adding package 'Respond.1.2.0' to folder 'C:\app\packages'
Added package 'Modernizr.2.6.2' to folder 'C:\app\packages'
Added package 'Respond.1.2.0' to folder 'C:\app\packages'
Added package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8' to folder 'C:\app\packages'
Added package 'Microsoft.AspNet.WebPages.3.2.3' to folder 'C:\app\packages'
Adding package 'Microsoft.ApplicationInsights.2.2.0' to folder 'C:\app\packages'
Added package 'Microsoft.ApplicationInsights.2.2.0' to folder 'C:\app\packages'
Adding package 'bootstrap.3.4.1' to folder 'C:\app\packages'
Added package 'bootstrap.3.4.1' to folder 'C:\app\packages'
Adding package 'WebGrease.1.5.2' to folder 'C:\app\packages'
Added package 'WebGrease.1.5.2' to folder 'C:\app\packages'
Adding package 'Microsoft.ApplicationInsights.Agent.Intercept.2.0.6' to folder 'C:\app\packages'
Added package 'Microsoft.ApplicationInsights.Agent.Intercept.2.0.6' to folder 'C:\app\packages'
Adding package 'Newtonsoft.Json.6.0.4' to folder 'C:\app\packages'
Added package 'Newtonsoft.Json.6.0.4' to folder 'C:\app\packages'
Adding package 'Microsoft.Net.Compilers.2.4.0' to folder 'C:\app\packages'
Added package 'Microsoft.Net.Compilers.2.4.0' to folder 'C:\app\packages'

NuGet Config files used:
    C:\Users\ContainerAdministrator\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json

Installed:
    27 package(s) to packages.config projects
Removing intermediate container bbaf29eac7f1
 ---> 9f0319ca76ce
Step 7/12 : COPY aspnetmvcapp/. ./aspnetmvcapp/
 ---> 93490b35f9d4
Step 8/12 : WORKDIR /app/aspnetmvcapp
 ---> Running in 0a5c86c32835
Removing intermediate container 0a5c86c32835
 ---> 198339a45031
Step 9/12 : RUN msbuild /p:Configuration=Release
 ---> Running in 60e2e1ca52b0
docker : The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; msbuild /p:Configuration=Release' returned a non-zero code: 1
At line:1 char:1
+ docker build --pull -t aspnetmvcapp .
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The command 'po...on-zero code: 1:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

PS C:\aspnetmvcapp>

**Comment by mthalman** [comment] 2020-02-24 14:05
I'm wondering whether you're running into this [1B host/2B container issue](https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t).  Can you compare the Windows version between your Docker container and your Docker host?  They should be the same in order for this to work because of this compatibility issue.  You can get the Windows version of the container by running this command:
```
docker pull mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
docker run --rm mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 cmd /C ver
```
It should be `10.0.17763.1040`.  If you run the `ver` command on the Docker host, it should have the same version if the latest security updates are applied.

**Comment by mjacob-cald** [comment] 2020-02-24 18:30
my host windows version is: Microsoft Windows [Version 10.0.17763.973]. Its few numbers off. So, is this issue caused by this? Also, I am pulling the mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

**Comment by mthalman** [comment] 2020-02-24 18:35
Yes, that's the cause of the issue as documented [here](https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t).  You need to ensure your Docker host machine has been upgraded to the latest Windows update.

**Comment by mjacob-cald** [comment] 2020-02-24 21:43
I have installed the security update and my windows version is now on Microsoft Windows [Version 10.0.17763.1039]

the docker build is now working without any issues. thank you.

**Comment by MichaelSimons** [comment] 2020-02-26 19:24
Closing as it was confirmed this was an [instance of Docker host machine not matching the container version issue.](https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t)

**Closed by MichaelSimons** 2020-02-26 19:24 UTC
