### ISSUE TITLE
Problems with COM References

### ISSUE THREAD

**Issue by johnnyasantoss** [microsoft/dotnet-framework-docker#145] opened 2018-05-11 14:37 UTC
I'm having difficulties to get a working build with a solution that has a project with a COMReference.

Here's my Dockerfile:
```dockerfile
FROM microsoft/dotnet-framework:4.7.1-sdk AS build

WORKDIR /deps/
COPY ./deps.dll ./register_deps.ps1 ./
RUN [ "powershell", "./register_deps.ps1" ]

WORKDIR /build
COPY ./MySolution.sln ./
COPY ./nuget.config ./
COPY ./src/MyProject/MyProject.csproj ./src/MyProject/
COPY ./src/MyProject.Deps/MyProject.Deps.csproj ./src/MyProject.Deps/

RUN msbuild /t:Restore /p:Configuration="Release"

COPY . .

RUN msbuild /t:Publish /m /p:Configuration="Release" /p:OutputPath=C:/app /p:NoWarn="NU1605"
```
The `register_deps.ps1` basically just runs `/Windows/SysWoW64/regsvr32 /s /i deps.dll`

When running the msbuild **publish** task it throws this error:

```
(ResolveComReferences target) ->                                                                                                       
                        C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2725,5): error MSB3091: Task failed because "AxImp.exe" was not found, or the correct Microsoft Windows SDK is not installed.
The task is looking for "AxImp.exe" in the "bin" subdirectory beneath the location specified in the InstallationFolder value of the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.1\WinSDK-NetFx40Tools-x86. 
  You may be able to solve the problem by doing one of the following:  
1) Install the Microsoft Windows SDK.  
2) Install Visual Studio 2010.  
3) Manually set the above registry key to the correct location.  
4) Pass the correct location into the "ToolPath" parameter of the task.
```

I don't know much about the file structure of this container to fix the tool path, so some help would be appreciated. :smile:

**Comment by johnnyasantoss** [comment] 2018-06-13 17:13
Any thoughts|recommendations|questions on this issue?? :frowning_face:

**Comment by ocean2002n** [comment] 2018-12-28 03:08
I got the same problem. Any recommendation?

**Comment by johnnyasantoss** [comment] 2018-12-31 12:08
My personal recommendation is: use `Linux containers` if it is possible for you.

**Comment by MichaelSimons** [comment] 2019-08-21 18:32
@Mthalman - Can you check if this will be addressed with VS 16.3?

**Comment by mthalman** [comment] 2019-08-23 17:56
@johnnyasantoss, @ocean2002n - Can either of you provide a project that repros this behavior?

**Comment by johnnyasantoss** [comment] 2019-08-25 08:20
Nop, sorry, it has been more than one year since I filed this bug. I no longer work with that project and in the end we chose to migrate to .netcore on Linux by removing/changing dependencies to others that supported .netstandard.

**Comment by MichaelSimons** [comment] 2020-04-27 15:01
AxImp.exe is included within the SDK images.

```
docker run --rm mcr.microsoft.com/dotnet/framework/sdk:4.8 cmd.exe /c "dir /s /r aximp.exe"
 Volume in drive C has no label.
 Volume Serial Number is 068B-86AD

 Directory of C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools

07/24/2019  03:07 PM            62,936 AxImp.exe
               1 File(s)         62,936 bytes

 Directory of C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64

07/24/2019  02:24 PM            62,424 AxImp.exe
               1 File(s)         62,424 bytes
```

The last two suggestions from the error stated in the origin issue description may be viable options.

```
3) Manually set the above registry key to the correct location.  
4) Pass the correct location into the "ToolPath" parameter of the task.
```

Closing because of no repo.  If you encounter this issue please open a new issue which includes steps that can be used to reproduce the issue.

**Closed by MichaelSimons** 2020-04-27 15:01 UTC
Labels: area:dockerfiles, category:sdk, enhancement, triaged
