### ISSUE TITLE
Unable to find messages file 'cscui.dll'

### ISSUE THREAD

**Issue by spriet2000** [microsoft/dotnet-framework-docker#416] opened 2019-09-20 12:36 UTC
Hello,

I am pretty stucked on this compilation problem. I suspect its a problem on the image. 

Since i am rebuilding the images, these compilation errors appear.

An error has occurred during compilation. error CS2018: Unable to find messages file 'cscui.dll'

Using latest mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2016

Details:

C:\BuildAgent\work\c560d714056a40bc\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(39, 5): The source file for this compilation can be found at: "C:\BuildAgent\temp\buildTmp\6c1d50b2-d3a1-48eb-9e4e-7833b25b44d9.txt"

C:\BuildAgent\work\c560d714056a40bc\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(39, 5): error MSB3758: An error has occurred during compilation. error CS2018: Unable to find messages file 'cscui.dll'

C:\BuildAgent\work\c560d714056a40bc\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(39, 5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property.

The path exists in the container 

/Windows/Microsoft.NET/Framework/v4.0.30319/1033/cscui.dll

I don't think the file is corrupt. Because I replaced it after a couple of tests with a working version.

I suspect a problem with the image, but I am not sure. 

Can you give a clue how to debug this further?

Greetings Rene

**Comment by MichaelSimons** [comment] 2019-09-24 14:16
@spriet2000 - Can you please provide a set of steps to reproduce this?

**Comment by spriet2000** [comment] 2019-09-25 13:39
That would be quite hard without sending my code, but I will try by making some custom code.

**Comment by spriet2000** [comment] 2019-09-27 08:09
I playing around with this. 

In a container which fails:

The cscui.dll exists in msbuild folder.
But it doesnt exist in windows/system32 folder

In a container which works:

The cscui.dll exists in msbuild folder.
The cscui.dll exists in windows/system32 folder

Copying a cscui.dll from system to the container system32 introduces a new error

Cannot resolve dependency to assembly 'Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.

Probably because its searching for other dependencies.

For now my theory is this cscui.dll is removed from windows image, but the Microsoft.Build.Utilities.Core still depends on it. 

When compilation I suspect the error is triggered by [Serializable] attribute.

I have to verify all this. But it sounds logical. Not sure if/how system32/cscui.dll is related to Microsoft.Build.Utilities.Core.

**Comment by MichaelSimons** [comment] 2019-10-02 18:39
@spriet2000 - Can you clarify which container you are using in which it works?

**Comment by MichaelSimons** [comment] 2019-10-16 18:37
Closing since a clear set of repro steps are not specified.  Feel free to re-open if you can provide a set of steps to reproduce the issue.

**Closed by MichaelSimons** 2019-10-16 18:37 UTC
