### ISSUE TITLE
Unable to run Windows Time Service within a container

### ISSUE THREAD

**Issue by DNikitenko** [Microsoft/dotnet-framework-docker#161] opened 2018-06-05 09:23 UTC
## Steps to reproduce the issue
1. Run _microsoft/dotnet-framework_ Docker container:
    `docker run -it --rm microsoft/dotnet-framework:4.7.2-runtime-20180508-windowsservercore-1803`
2. Enter `w32tm /register` command.
3. Enter `net start w32time` command.

## Expected behavior
The Windows Time Service is started successfully.

## Actual behavior
The service could not be started with the following error:

> The Windows Time service is starting.
> The Windows Time service could not be started.
> A system error has occurred.
> System error 5 has occurred.
> Access is denied.

## Additional information (e.g. issue happens only occasionally)
My application requires Windows Time Service to be enabled. A typical problem resolution which I see in web for the error like that is to run those commands from an elevated cmd/powershell. But I'm already an administrative user (_ContainerAdministrator_).
Also I've tried to enable administrator user and to run a .ps1 script with the same commands from an Administrator account - and it's all the same.

## Output of `docker version`

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

## Output of `docker info`

```
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 14
Server Version: 18.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.8GiB
Name: WSW-1HWKXF2
ID: PKZF:AMLV:BOME:SZZM:RFTD:YVFA:JGBU:WLAC:K4CV:KKHP:EBFD:AY5U
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 57
 System Time: 2018-05-30T17:35:19.0461548+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment] 2018-06-05 14:07
@DNikitenko - this appears to be a duplicate of https://github.com/dotnet/dotnet-docker/issues/559.  This issue is specific to the microsoft/windowsservercore:1803 OS base image.  Did you follow up with the [Windows Container Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers)?

**Comment by DNikitenko** [comment] 2018-06-05 14:44
@MichaelSimons Yes, there I was asked to create a ticket [here](https://social.msdn.microsoft.com/Forums/en-US/e5cd78f1-2f71-47b2-99a5-c3aca8d57b26/unable-to-run-windows-time-service-within-a-docker-container?forum=windowscontainers)

**Comment by MichaelSimons** [comment] 2018-06-05 15:30
@DNikitenko - I apologize but this issue is not specific to the microsoft/dotnet-framework images.  There is nothing that can be done here to address the issue.  This appears to be an issue with the microsoft/windowsservercore:1803 OS base image.  I would suggest simplifying your repro steps down to the simplest scenario and follow up on the forum.

**Comment by MichaelSimons** [comment] 2018-06-06 14:13
Closing as this issue is not specific to the microsoft/dotnet-framework images.  It can be reproduced in the microsoft/windowsservercore:1803 or microsoft/windowsservercore:1709 OS base images.

**Closed by MichaelSimons** 2018-06-06 14:13 UTC
