### ISSUE TITLE
not support visual studio 2017

### ISSUE THREAD

**Issue by liucc52** [Microsoft/dotnet-framework-docker#172] opened 2018-07-10 01:53 UTC
msbuild /version
Microsoft (R) core version 14.0.25123.0
Copyright (C) Microsoft Corporation。 all rights reserved.

error info 
 The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by MichaelSimons** [comment] 2018-07-11 16:47
@liucc52, Can you please provide detailed steps to reproduce the error you have included?  There isn't enough information provided to know what the problem is.  How does this relate to the microsoft/dotnet-framework Docker images?

**Comment by MichaelSimons** [comment] 2018-07-18 14:58
Closing because not enough information was provided.  Feel free to update with the requested details and reopen.

**Closed by MichaelSimons** 2018-07-18 14:58 UTC
