### ISSUE TITLE
Provide support for SDK-only releases

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#253] opened 2019-04-02 17:27 UTC
In some cases there's a need to only update the SDK images and not the runtime.   There are issues with the tests and ImageBuilder that prevent this, requiring that the runtime images also be built.

**Comment by MichaelSimons** [comment] 2019-05-22 21:47
Closing this as a duplicate of https://github.com/dotnet/docker-tools/issues/186

**Closed by MichaelSimons** 2019-05-22 21:47 UTC
Labels: area:infrastructure, duplicate, enhancement, triaged
