### ISSUE TITLE
Create tests that are run as part of CI that verify LCU is applied correctly

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/dotnet-framework-docker#85] opened 2018-01-31 20:10 UTC
Currently this is done through a manual process.  Would be valuable to automate this and have it run as part of CI.

**Comment by mthalman** [comment] 2023-07-05 18:56
Duplicate of https://github.com/microsoft/dotnet-framework-docker/issues/873

**Closed by mthalman** 2023-07-05 18:56 UTC
Labels: enhancement, area-infrastructure, category-runtime
