### ISSUE TITLE
Can not build container image with extra components for windowsservercore-ltsc2019 fails but not for windowsservercore-ltsc2022

### ISSUE THREAD

**Issue by bleissem** [microsoft/dotnet-framework-docker#858] opened 2021-11-29 22:14 UTC
### Describe the Bug
A github actions build fails for windowsservercore-ltsc2019 by installing some extra components
as you can see here:
https://github.com/bleissem/dotnet-framework-docker/actions/runs/1517979523
build definition:
https://github.com/bleissem/dotnet-framework-docker/blob/main/.github/workflows/windows2019.yml
dockerfile:
https://github.com/bleissem/dotnet-framework-docker/blob/main/src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile

By using the windowsservercore-ltsc2022 dockerfile the build does not fail
as you can see here:
https://github.com/bleissem/dotnet-framework-docker/actions/runs/1517979519
build definition:
https://github.com/bleissem/dotnet-framework-docker/blob/main/.github/workflows/windows2022.yml
dockerfile:
https://github.com/bleissem/dotnet-framework-docker/blob/main/src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile

### Steps to Reproduce
may run build again with the fork
https://github.com/bleissem/dotnet-framework-docker
or use the extra component id's:

    # https://docs.microsoft.com/de-de/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2022
        --add Microsoft.Component.MSBuild;includeRecommended ^ `
        --add Microsoft.VisualStudio.Workload.DataBuildTools;includeRecommended ^ `          
        --add Microsoft.VisualStudio.Workload.NetCoreBuildTools;includeRecommended ^ `
        --add Microsoft.VisualStudio.Component.TestTools.BuildTools;includeRecommended ^ `
        --add Microsoft.VisualStudio.Workload.WebBuildTools;includeRecommended ^ `
        --add Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools;includeRecommended ^ `
        --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools;includeRecommended ^ `
    # https://docs.microsoft.com/de-de/visualstudio/install/workload-component-id-vs-community?view=vs-2022        
        --add Microsoft.VisualStudio.Workload.NetWeb;inlcudeOptional ^ `    
        --add Microsoft.VisualStudio.Component.Git ^ ` 
for building         
https://github.com/microsoft/dotnet-framework-docker/blob/main/src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile

**Comment by mthalman** [comment] 2021-11-30 20:38
The error is coming from the `ngen update` command. After digging into that command, I saw this in the output:

```
Failed to compile C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe because this image is a 64bit assembly; try using 64bit ngen instead.
```

So the problem is that the VS Build Tools registered the TF.exe, a 64-bit file, to be queued for the 32-bit version of ngen. This is clearly a bug and is likely the result of the migration to 64-bit for VS proper. I'll let the VS team know about this.

Why this only happens for Server 2019 and not Server 2022, I haven't dug into that yet.

To work around this, you can unregister the file to prevent the attempt to ngen it when running `ngen update`. Just add this command before running `ngen update`:

```
%windir%\Microsoft.NET\Framework\v4.0.30319\ngen uninstall "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe"
```

**Comment by mthalman** [comment] 2021-11-30 20:53
For tracking purposes, this is the link to the internal bug I logged for VS: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1444002/

**Comment by mthalman** [comment] 2021-11-30 22:11
Also, be aware that the `Microsoft.VisualStudio.Workload.NetCoreBuildTools` component no longer exists in the VS 2022 Build Tools installer. This is referenced in your Dockerfiles and it ends up being ignored with a warning in the installer log file that it doesn't exist.

Can I ask why you are recreating the entire SDK Dockerfile and adding the extra VS components rather than base it on the SDK image and only install the extra VS components you require?

**Comment by bleissem** [comment] 2021-12-02 09:35
Hello @mthalman , thanks for looking into this. 
About your question: "Can I ask why you are recreating the entire SDK Dockerfile and adding the extra VS components rather than base it on the SDK image and only install the extra VS components you require?"
Well it would be indeed logical to do so.
Because the vs_BuildTools.exe  is deleted in the original Dockerfile it somehow has to be downloaded again to rerun the setup.
And because there are comments like "Workaround " in the Dockerfile I thought that to would be better to use the original Dockerfile as a blueprint to avoid errors etc. that I'm not aware of. 
Also using the original Dockerfile as a blueprint enables me to ask for some kind of support. ( This issue can also be regarded as asking for support.)
It would be nice if  a docker image can be provided which is capable of running the  vs_BuildTools.exe to install additional components if needed. 
Regards
Alex B.

**Comment by mthalman** [comment] 2021-12-02 16:40
Acquiring vs_BuildTools.exe is pretty simple when using the aka.ms link. We have [documentation](https://docs.microsoft.com/visualstudio/install/build-tools-container?view=vs-2022) for doing this scenario of including additional components to the VS Build Tools installation on top of the sdk image. Check that out.

**Comment by bleissem** [comment] 2021-12-08 11:37
Hello @mthalman , thanks for providing the documentation link. Just because I'm curious to know, why is there a difference between the dockerfile that is provided in the documentation and the dockerfile that you use for 
https://github.com/microsoft/dotnet-framework-docker/blob/main/src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
( for example the lines with # Workaround for issues with 64-bit ngen ) ? 
Regards 
Alex B.

**Comment by mthalman** [comment] 2021-12-08 13:46
The ngen workaround only needs to be once. Since the Dockerfile used in the documentation is based on the sdk image, it already has the workaround applied.

**Comment by mthalman** [comment] 2021-12-08 19:48
Triage: Closing per the guidance on [working around the ngen issue](https://github.com/microsoft/dotnet-framework-docker/issues/858#issuecomment-983000852). Feel free to respond with further questions on making use of the base sdk image.

**Closed by mthalman** 2021-12-08 19:48 UTC
Labels: bug, area-dockerfiles, untriaged
