### ISSUE TITLE
msbuild.exe does not work in latest sdk:4.8 image

### ISSUE THREAD

**Issue by chrishaland** [microsoft/dotnet-framework-docker#524] opened 2020-02-24 16:59 UTC
## Steps to reproduce the issue
1. docker pull mcr.microsoft.com/dotnet/framework/sdk:4.8
2. docker run -it --rm mcr.microsoft.com/dotnet/framework/sdk:4.8 powershell
3. msbuild -help

## Expected behavior
msbuild version information, options and examples are printed to the console

## Actual behavior
msbuild exits with exit code 3221225785 and does not print anything to the console

## Additional information (e.g. issue happens only occasionally)
Our 4.8 tag resolves to mcr.microsoft.com/dotnet/framework/sdk@sha256:0008d5d893924c10ec01b1619a009c57116f9a943fe43ca772af544c75c9a83a

**Comment by mthalman** [comment] 2020-02-24 17:02
Duplicate of https://github.com/microsoft/dotnet-framework-docker/issues/521

**Closed by mthalman** 2020-02-24 17:02 UTC
