### ISSUE TITLE
.NET Framework 4.8 website builds are failing with the microsoft 4.8 images

### ISSUE THREAD

**Issue by pradeep864** [microsoft/dotnet-framework-docker#751] opened 2021-04-06 16:04 UTC
### Describe the Bug
Website builds started failing from 3/30/2021 using the below docker images 
mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
mcr.microsoft.com/dotnet/framework/sdk:4.8

### Steps to Reproduce
Build website using 
images: 
mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
mcr.microsoft.com/dotnet/framework/sdk:4.8 
Framework: .NET framework 4.8

### Other Information

C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014: The build stopped unexpectedly because of an internal failure.
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014: System.NotSupportedException: The given path's format is not supported.
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at Microsoft.Build.Construction.ProjectInSolution.get_AbsolutePath()
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.AddPropertyGroupForSolutionConfiguration(ProjectRootElement msbuildProject, SolutionFile solutionFile, SolutionConfigurationInSolution solutionConfiguration)
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.CreateTraversalInstance(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified, List`1 projectsInOrder)
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.CreateSolutionProject(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified)
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.Generate()
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapper(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, BuildEventContext projectBuildEventContext, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildRequest request)
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
C:\src\xxxxxxxxxxxxxxx.sln : error MSB4014:    at Microsoft.Build.Execution.BuildManager.IssueBuildSubmissionToScheduler(BuildSubmission submission, Boolean allowMainThreadBuild)

Build FAILED.

### Output of `docker version`

Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:26:56 2021
  OS/Arch:          windows/amd64
  Experimental:     false

### Output of `docker info`

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 30
 Server Version: 20.10.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows 10 Enterprise Version 1809 (OS Build 17763.1817)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.52GiB
 Name: GEN8211-19
 ID: CM3S:UCI7:WKOB:B6XM:SVNT:3FOB:6XIO:IMOV:2CDJ:6SZS:6KRL:6TVM
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by MichaelSimons** [comment] 2021-04-07 18:21
[Triage] @pradeep864 - Can you provide some more context?  If possible please provide a set of steps that can be used to reproduce the issue.

**Comment by pradeep864** [comment] 2021-04-07 18:30
@MichaelSimons  - Here are some of the steps from my Dockerfile.  Mhy project type is .NET framework website

### Download Windows server image and 4.8 SDK
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019 AS base
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build

WORKDIR /src
COPY xxxxxxxxxxxx.sln .
COPY xxxxxxxxxxxx/. ./xxxxxxxxxxxx/

RUN msbuild /p:DeployOnBuild=true

**Comment by MichaelSimons** [comment] 2021-04-07 18:56
@pradeep864, Can you share your Solution and Dockerfile?  It is difficult to diagnose without a concrete repro.

**Comment by pradeep864** [comment] 2021-04-07 20:43
@MichaelSimons Sorry about that. Is the solution file, web.config and docker file enough or do I need to share the complete solution?

**Comment by MichaelSimons** [comment] 2021-04-08 13:00
Sharing the complete solution would be the most helpful as it would allow us to build and attempt to reproduce the problem you encountered.  Alternatively, can you create a simplified project that reproduces the scenario?

**Comment by pradeep864** [comment] 2021-04-09 15:46
Hi @MichaelSimons  Please find the attached sample. This is exact solution I am trying to build with trimmed functionality.  I hope this helps you to reproduce the issue.
[dockerbuildissue.zip](https://github.com/microsoft/dotnet-framework-docker/files/6286936/dockerbuildissue.zip)

**Comment by MichaelSimons** [comment] 2021-04-14 16:30
To clarify, does the issue reproduce for you with the sample you attached?  I am unable to reproduce the issue with the attached sample using `docker build -t test --pull .`.  The `RUN msbuild` step succeeded.  After that I encountered syntax issues within the Dockerfile at `COPY --from=build /src/PrecompileWeb/NET48DockerBuildTest/. ./`.

Given the exception message included in the original issue, have you tried passing in the project or solution path into your msbuild command?

**Comment by pradeep864** [comment] 2021-04-14 20:20
Hi @MichaelSimons - Thanks a lot for looking into this.  Build is working fine for me. I noticed some issue with the from command and I will try to fix that.

I am pretty confident there has been an update to the Microsoft images in my docker file.  When I ran the build today, it pulled down latest images. Please see the attached file.
![dockerbuildissue](https://user-images.githubusercontent.com/36279011/114773215-60091400-9d34-11eb-83ae-a997d8c967b6.png)

**Comment by MichaelSimons** [comment] 2021-04-14 20:26
Yes the new images were released yesterday.  Our Windows images are updated every Patch Tuesday (2nd Tuesday of the month).

Are you saying the issue has been resolved?  If so feel free to close this issue.  Otherwise please send me the exact instructions you are using with the sample project you included earlier and the error you get.

**Comment by pradeep864** [comment] 2021-04-14 21:12
The issue has been resolved now with the new image. Thank you for your time on this.
Is there a place I can see the change log for the image updates/patches? We are using these images in production and this caused issues in our release schedule.  We had to hold off on deploying more changes because of the build failure.  Could you suggest how we can avoid this in the future?

**Comment by MichaelSimons** [comment] 2021-04-15 13:42
There are two places you can get this information from.  

1. The dotnet/versions repo captures the information about the images, what their digests are, what commit sha they were built with etc. Reviewing the commit history is helpful.  [Here](https://github.com/dotnet/versions/blob/main/build-info/docker/image-info.microsoft-dotnet-framework-docker-main.json) is the versions file for the dotnet/framework images.
2. The source Dockerfiles (e.g. [ltsc2019 sdk Dockerfile](https://github.com/microsoft/dotnet-framework-docker/blob/main/src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile)) and history show the changes that were made to the images.  Because the `sdk` images is built on the `runtime` image, you will have to look at both Dockerfiles to see the complete picture.

The .NET FX images are typically only updated on Patch Tuesday.  Your original description stated the regression occurred March 30.  There were no image rebuilds around this time.

Closing as the issue is no longer reproducible.

**Closed by MichaelSimons** 2021-04-15 13:42 UTC
Labels: area-infrastructure, bug, untriaged

**Comment by pradeep864** [comment] 2021-04-15 13:53
Thanks for providing the information.
