### ISSUE TITLE
Image with tag 4.8-windowsservercore-ltsc2022 generate 403 error by default

### ISSUE THREAD

**Issue by Ducatel** [microsoft/dotnet-framework-docker#1130] opened 2024-05-23 09:55 UTC
### Describe the Bug

When you run `docker run -ti --rm -p 80:80 mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022` and access to the container on port 80, you face a 403 error

![image](https://github.com/microsoft/dotnet-framework-docker/assets/1184332/8712909f-2556-4a8d-95b3-d6d05d5a67ef)

### Steps to Reproduce

just run `docker run -ti --rm -p 80:80 mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022` 

### Other Information

Seems to display the IIS default webpage with the tag `4.8` when I'm on windows 10 desktop

### Output of `docker version`

```
Client:
 Cloud integration: v1.0.35+desktop.13
 Version:           26.1.1
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        4cf5afa
 Built:             Tue Apr 30 11:48:43 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.30.0 (149282)
 Engine:
  Version:          26.1.1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       ac2de55
  Built:            Tue Apr 30 11:47:32 2024
  OS/Arch:          windows/amd64
  Experimental:     false

```

### Output of `docker info`

```
Client:
 Version:    26.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.29
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.8.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 35
 Server Version: 26.1.1
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Microsoft Windows Server Version 21H2 (OS Build 20348.2461)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 16GiB
 Name: xxxxxxxx
 ID: 566c5632-0efc-42ea-af54-58f217c422c7
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

Thanks in advance for your help

**Comment by lbussell** [comment] 2024-05-23 16:24
I can get the same result ("403 - Forbidden") using the following tags/digests:
- `mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2016` (`sha256:20e7045e873476641a3e8cfe182d2401d94feea856816b31613e16fb7a53e664`)
- `mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019` (`sha256:b7be163b2b65da14d4552cc03037134a89d9d739200e0ffeb84bd03e378e0d7a`)
- `mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022` (`sha256:e9aa4e7571b3914a5a0c07c934ad572ef055123df705586ab5803ea3bf83453a`)
- `mcr.microsoft.com/dotnet/framework/aspnet:4.8` (which resolves to `4.8-windowsservercore-ltsc2016` on my Windows 11 host (due to https://github.com/containerd/containerd/issues/6508).

I would like to determine if this affects all versions or just Server 2022 for you.

@ducatel Since the behavior is different for the `4.8` and `4.8` Server 2022 tags for you, I suspect you have an old version of the 4.8 tag pulled locally. If you can get the digest(s) for that tag, we can try and determine what caused the behavior change.

What is the output of `docker manifest inspect mcr.microsoft.com/dotnet/framework/aspnet:4.8` on your host *without* running `docker pull` first? I would expect the manifest list to not match the above digests, which are the latest ones.

`docker images mcr.microsoft.com/dotnet/framework/aspnet:4.8` will also tell you the created date of the manifest list.

**Comment by Ducatel** [comment] 2024-05-24 08:36
Here you have the manifest output

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2635,
         "digest": "sha256:20e7045e873476641a3e8cfe182d2401d94feea856816b31613e16fb7a53e664",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.14393.6981"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2633,
         "digest": "sha256:b7be163b2b65da14d4552cc03037134a89d9d739200e0ffeb84bd03e378e0d7a",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.5820"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2424,
         "digest": "sha256:e9aa4e7571b3914a5a0c07c934ad572ef055123df705586ab5803ea3bf83453a",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.20348.2461"
         }
      }
   ]
} 
```

**Comment by lbussell** [comment] 2024-06-14 22:46
Hey @Ducatel, I was able to reproduce this, but notably, I couldn't notice any issues when actually running a real ASP.NET app. For example, our ASP.NET sample: https://github.com/microsoft/dotnet-framework-docker/tree/main/samples/aspnetapp

I also passed this along to our ASP.NET team and they didn't find any regressions. I'm closing this is not planned since running the aspnet image without deploying an app is not an expected scenario.

**Closed by lbussell** 2024-06-14 22:46 UTC
Labels: bug, untriaged
