### ISSUE TITLE
Feature Request: Framework SDK Images based on Full Windows

### ISSUE THREAD

**Issue by grochoge** [microsoft/dotnet-framework-docker#1009] opened 2022-09-27 17:36 UTC
### Describe the Problem

I am trying to use ADO (not .NET) and Jet to access an Access database file (.mdb). It appears the Jet OLE DB libraries are not part of Windows Server Core but are part of full Windows.

### Describe the Solution

Add SDK tags based on full Windows (e.x. docker pull mcr.microsoft.com/windows:ltsc2019) in addition to those based on Windows Server Core.

### Additional Context

N/A

**Comment by mthalman** [comment] 2022-09-27 17:46
Duplicate of https://github.com/microsoft/dotnet-framework-docker/issues/433. We'll use that as the primary request for this feature.

**Closed by mthalman** 2022-09-27 17:46 UTC
Labels: enhancement, area-dockerfiles, untriaged
