### ISSUE TITLE
msbuild not giving any output

### ISSUE THREAD

**Issue by Icaroto** [microsoft/dotnet-framework-docker#518] opened 2020-02-18 15:30 UTC
## Steps to reproduce the issue
I have a dockerfile that uses  sdk:4.7.2-windowsservercore-ltsc2019and basically it's supposed to just build a Visual Studio solution using msbuild. Until a few days ago it was working fine, now msbuild doesn't give any response. 

## Steps to reproduce
I'm using the below dockerfile:
```
# escape=`
FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.2-windowsservercore-ltsc2019 AS builder
LABEL maintainer="testing"
CMD ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV NUGET_PATH="C:\Chocolatey\lib\NuGet.CommandLine.5.4.0\tools" `
    NUNIT_PATH="C:\NUnit.ConsoleRunner.3.8.0\tools" `
    OCTO_PATH="C:\Chocolatey\lib\OctopusTools.6.17.0\tools"

RUN $env:PATH = $env:OCTO_PATH + ';' + $env:NUGET_PATH + ';' + $env:NUNIT_PATH + ';' + $env:PATH; `
	[Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine);

RUN Install-PackageProvider -Name chocolatey -RequiredVersion 2.8.5.130 -Force; `
    Install-Package nuget.commandline -RequiredVersion 5.4.0 -Force; `    
    & nuget install NUnit.ConsoleRunner -Version 3.8.0; `
    Install-Package googlechrome -Force; `
    Install-Package octopustools -RequiredVersion 6.17.0 -Force

WORKDIR c:\build
COPY . .
RUN msbuild -v
ENTRYPOINT ["powershell"]
```

And I am triggering it from Jenkins using the following (considering both are in a repo):

```
def generateImageName() {
  jobName = env.JOB_NAME.toLowerCase().replaceAll(/[\s-]|\/|%2f/, '.')
  return "${jobName}_${env.BUILD_NUMBER}"
}

def imageName = generateImageName()
def image

pipeline {
  agent {
    label 'IE1SFBLD02'
  }

  stages {
    stage('Setup Docker image') {
      steps {    
	  library 'shared-library'
        script {
          image = docker.build(imageName)
        }
      }
    }
   
    stage('Clean Workspace') {
      steps {
        cleanWs()
      }
    }
  }
}
```

## Expected behavior
See the version of msbuild.

## Actual behavior
```
Sending build context to Docker daemon  5.863MB

Step 1/11 : FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.2-windowsservercore-ltsc2019 AS builder
 ---> 1afb4e8593d8
Step 2/11 : LABEL maintainer="testing"
 ---> Using cache
 ---> 50a9522af4f3
Step 3/11 : CMD ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
 ---> Using cache
 ---> 739e71cd8f37
Step 4/11 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Using cache
 ---> 7817918aed13
Step 5/11 : ENV NUGET_PATH="C:\Chocolatey\lib\NuGet.CommandLine.5.4.0\tools"     NUNIT_PATH="C:\NUnit.ConsoleRunner.3.8.0\tools"     OCTO_PATH="C:\Chocolatey\lib\OctopusTools.6.17.0\tools"
 ---> Using cache
 ---> 1a2c45e99c46
Step 6/11 : RUN $env:PATH = $env:OCTO_PATH + ';' + $env:NUGET_PATH + ';' + $env:NUNIT_PATH + ';' + $env:PATH; 	[Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine);
 ---> Using cache
 ---> c48de751f82c
Step 7/11 : RUN Install-PackageProvider -Name chocolatey -RequiredVersion 2.8.5.130 -Force;     Install-Package nuget.commandline -RequiredVersion 5.4.0 -Force;     & nuget install NUnit.ConsoleRunner -Version 3.8.0;     Install-Package googlechrome -Force;     Install-Package octopustools -RequiredVersion 6.17.0 -Force
 ---> Using cache
 ---> f9d3ba7532dc
Step 8/11 : WORKDIR c:\build
 ---> Using cache
 ---> aca4d0473026
Step 9/11 : COPY . .
 ---> 8df4748dc4e3
Step 10/11 : RUN msbuild -v
 ---> Running in 90f136016d68
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; msbuild -v' returned a non-zero code: 1
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Clean Workspace)
Stage "Clean Workspace" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

When I enter the container and try to execute msbuild from withing I get no output, no error, no message, just a new line. Eg:
```
PS C:\build> msbuild
PS C:\build>
```

## Output of `docker version`
```
Docker version 19.03.5, build 633a0ea
```

## Output of `docker info`
```
Client:
 Debug Mode: false

Server:
 Containers: 32
  Running: 0
  Paused: 0
  Stopped: 32
 Images: 67
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1039)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7GiB
 Name: IE1SFBLD02
 ID: ABVO:XGYI:4VOU:SCX7:X3RH:YSP4:65BD:Z7IS:JOWV:UXUF:LF7Q:DO5P
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 28
  System Time: 2020-02-18T16:46:18.0233313Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by MichaelSimons** [comment] 2020-02-18 15:39
@Icaroto, Can you please provide more details? A set steps that can be used to reproduce the issue would be the most helpful.  Also please provide the output of `docker info`.

**Comment by Icaroto** [comment] 2020-02-18 16:49
Hi @MichaelSimons  I've just added more details. Hope they are useful.

**Comment by MichaelSimons** [comment] 2020-02-18 17:07
@lcaroto, What is your Docker build context?  What are the contents getting copied into the image via `COPY . .`?  Have you verified the contents are what you expect?  e.g. is your project getting copied into the image?  When you enter your container have you inspected the contents of `c:\build`?

**Comment by Icaroto** [comment] 2020-02-18 17:17
COPY is adding my solution to a specific directory (I should have removed this one as it doesn't affect the issue).  All it's working fine and in the proper place (regarding the solution). 

The command "msbuild" itself is the thing not working. Even without the solution to build. A simple "msbuild -v" doesn't return no output. 

If I enter the container with "docker run -it" and try to execute a "msbuild -v" from there, I get no response/output at all.

**Comment by sylus** [comment] 2020-02-18 20:20
Having this exact same problem that occurred once one of our windows node in AKS got updated.

**Comment by ryandzink** [comment] 2020-02-19 05:55
I'm seeing this issue on an AWS EC2 host running this AMI: Windows_Server-2016-English-Full-ContainersLatest-2020.02.12 (ami-0c60b97cae5e54e63). Trying to do a `docker run -it mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2016` and executing msbuild in the container exits immediately. It doesn't yet look like Amazon has rolled a newer version of the 2016 AMI, but it should appear within the next couple of days to hopefully resolve the problem.

**Comment by mthalman** [comment] 2020-02-19 13:36
Pretty sure this is related to https://support.microsoft.com/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t.  The problem is that there's a mismatch between the Windows version of the Docker host and the container.  They need to match in order for this problem to be resolved.

We're currently in the process of getting updated .NET Framework Docker images published which will update the images to use the latest version of Windows.  This had been blocked before because of https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im.

You can follow progress of the release at https://github.com/microsoft/dotnet-framework-docker/issues/513.

**Comment by sylus** [comment] 2020-02-19 13:37
So when we rebuild our containers and matched 1039 everything started to work again :D 

`4.8/runtime/windowsservercore-ltsc2019`

FROM mcr.microsoft.com/windows/servercore:10.0.17763.1039

`4.8/sdk/windowsservercore-ltsc2019`

ARG REPO=artifactory.cloud.xxx.ca/docker/dotnet/framework/runtime
FROM $REPO:4.8-windowsservercore-10.0.17763.1039

Then we could use that final artifact and everything worked fine :D

**Comment by MichaelSimons** [comment] 2020-02-19 17:01
It looks like this is a symptom of a [regression caused by the Windows Server Feb 11, 2020 security updates](https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t).  The .NET Framework images were just rebuilt with the latest Windows images which contain a fix for this issue.  Please re-pull the .NET Framework images and retry your scenarios.

**Comment by MichaelSimons** [comment] 2020-02-19 19:06
Closing per the previous response.  Please let us know if you are still seeing issues with the latest response.

**Closed by MichaelSimons** 2020-02-19 19:06 UTC

**Comment by Icaroto** [comment] 2020-02-20 16:23
Hi @MichaelSimons 
Do I need to do anything else apart from getting the new images?
I removed all containers and all images I had and got a fresh copy from 4.7.2-windowsservercore-ltsc2019

I am still having the silently error. And notice that the image have the 10.0.17763.805 windows version opposite to the machine running it, where I have 10039.

Am I missing a step?

**Comment by mthalman** [comment] 2020-02-20 16:45
4.7.2 SDK images are no longer being published.  Please see https://github.com/microsoft/dotnet-framework-docker/issues/428.  You should update to use the `4.8-windowsservercore-ltsc2019` tag.

**Comment by Icaroto** [comment] 2020-02-21 10:52
I switched to 4.8 and it sorted the build issues!Thanks!

I wonder if the new version could have break something around Powershell? As the Install-Package commands are failing now. 
Could it be related somehow? 

```
install-package googlechrome -force
WARNING: NuGet: System.InvalidOperationException: Unable to find version '1.3.5.1' of package 'chocolatey-core.extension'.
```

**Comment by goonux** [comment] 2020-05-19 15:45
Hi @Icaroto , I'm facing exactly the same issue with your issue. 

-- **currently**
My windows container host is (Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.805)), I can still use the (mcr.microsoft.com/dotnet/framework/sdk:4.7.2-20191008-windowsservercore-ltsc2019) image for building my application, it's working well
-- **but**
When I use the latest AWS AMI - windows container host with the same sdk image above, nothing happened (msbuild is gone silently)
--
My application is running with .net framework 4.7.2, so the solution is we have to update our app framework from 4.7.2 to 4.8.x right? then we can use the sdk:4.8.x image to build the app on the new aws ami windows container host?

**Comment by Icaroto** [comment] 2020-05-19 20:04
Hi @goonux 

I might be wrong but I think you dont have to update your application, just the sdk image you are pulling. I didn't change anything on my application, just pointed to the 4.8 sdk and it was sorted :)

**Comment by goonux** [comment] 2020-05-24 02:00
Hi @Icaroto 
I've tried to your guide, but I got the Nuget package errors 

---- AWS Windows AMI 
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1217)

---  SDK image 
mcr.microsoft.com/dotnet/framework/sdk:4.8-20200211-windowsservercore-ltsc2019

---> the output errors of Nuget

error : Unable to find version '6.2.0' of package 'EntityFramework'
error : Unable to find version '2.2.2' of package 'Microsoft.AspNet.Identity.Core'
error : Unable to find version '2.2.2' of package 'Microsoft.AspNet.Identity.EntityFramework'

do you know how to fix that? please help

My app is still building fine on the sdk:4.7.x and the old windows ami aws.

**Comment by zenatureza** [comment] 2020-10-15 19:48
Having the same issue as @goonux . Can anyone help?

--- OS
Windows Server 2019 Standart Version 1809 (OS Build 17763.134)

--- SDK image
mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
*also tried with: mcr.microsoft.com/dotnet/framework/sdk:4.8

--- Error:
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; msbuild ManagerWeb.sln /t:Rebuild /p:outdir="c:\\app\\managerweb\\release\\" /p:Configuration=Release' returned a non-zero code: 1

**Comment by mthalman** [comment] 2020-10-15 19:53
@zenatureza - Please see the earlier [comment](https://github.com/microsoft/dotnet-framework-docker/issues/518#issuecomment-588328034) and follow the link to the support page describing the issue to learn more about this.  Basically, your SDK image is incompatible with your host OS; you'll most likely want to upgrade your host OS because it looks quite old based on the build version.

**Comment by zenatureza** [comment] 2020-10-15 21:22
@mthalman Thanks! Upgraded the os and worked perfectly.
