### ISSUE TITLE
MSBuild.exe error "exit status 3221225794"

### ISSUE THREAD

**Issue by draperj** [microsoft/dotnet-framework-docker#574] opened 2020-05-08 17:08 UTC
## Steps to reproduce the issue
1. Run Docker image mcr.microsoft.com/dotnet/framework/sdk:4.8-20200114-windowsservercore-ltsc2016 in AWS Codebuild
2. Run "MSBuild.exe *.csproj  -t:clean,restore,build -p:publishUrl=*,DeployOnBuild=True,DeployDefaultTarget=WebPublish,WebPublishMethod=FileSystem,Platform=AnyCPU,Configuration=Release,DebugType=None" Reason: exit status 3221225794

## Expected behavior
Successful build

## Actual behavior
Receive message:
[Container] 2020/05/08 15:58:15 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: MSBuild.exe *.csproj  -t:clean,restore,build -p:publishUrl=*,DeployOnBuild=True,DeployDefaultTarget=WebPublish,WebPublishMethod=FileSystem,Platform=AnyCPU,Configuration=Release,DebugType=None. Reason: exit status 3221225794

## Additional information (e.g. issue happens only occasionally)
Issue occurring as of today, image built correctly yesterday.

## Output of `docker version`

N/A, not available to obtain from AWS CodeBuild log.

## Output of `docker info`

N/A, not available to obtain from AWS CodeBuild log.

**Comment by mthalman** [comment] 2020-05-08 17:13
Duplicate of https://github.com/microsoft/dotnet-framework-docker/issues/548.  An explanation and resolution is provided in that issue.  Feel free to comment further if you have additional questions.

**Closed by mthalman** 2020-05-08 17:13 UTC
