### ISSUE TITLE
Not able to build project with ToolsVersion="15.0"

### ISSUE THREAD

**Issue by giusepanzuto** [Microsoft/dotnet-framework-docker#256] opened 2019-04-03 13:34 UTC
I'm using the image tagged as "microsoft/dotnet-framework:4.7.2-sdk" into my CI pipeline.
From today when I try to build I'm getting the following error:

Project file contains ToolsVersion="15.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333

Thanks
G.

**Comment by MichaelSimons** [comment] 2019-04-03 13:52
@giusepanzuto - any chance you can share your project?  VS 2019 was released yesterday which is more than likely the source of the issue.  To unblock yourself until the issue is resolved, you can use the pervious version - `mcr.microsoft.com/dotnet/framework/sdk:4.7.2-20190312-windowsservercore-ltsc2016` tag.

**Comment by mthalman** [comment] 2019-04-03 13:53
Related to #228 

It'd also be helpful to know what your Dockerfile looks like.

**Comment by giusepanzuto** [comment] 2019-04-03 14:32
> 
> 
> @giusepanzuto - any chance you can share your project? VS 2019 was released yesterday which is more than likely the source of the issue. To unblock yourself until the issue is resolved, you can use the pervious version - `mcr.microsoft.com/dotnet/framework/sdk:4.7.2-20190312-windowsservercore-ltsc2016` tag.

I confirm, it works correctly with the version 4.7.2-20190312-windowsservercore-ltsc2016, so I think that the issue is caused by the last update.

Unfortunately I cannot share code here, but I can confirm that we have the same issue with all software that are currently using pipeline with this image.

Thank you for the support.
G.

**Comment by mthalman** [comment] 2019-04-03 14:37
@giusepanzuto - Are you able to provide a simplified version of the project that can repro the issue?  As an example, there are projects in both the tests and samples folder of this repo which are using 15.0 for the ToolsVersion and they do not get such an error.

**Comment by MichaelSimons** [comment] 2019-04-03 14:50
@giusepanzuto - I understand not wanting to share the project here.  As @mthalman mentioned a standalone repo is preferred.  If you can't figure one out and you are willing to share it with me you can mail me @ msimons@ms.

**Comment by giusepanzuto** [comment] 2019-04-03 15:02
I'm try to create an example project... in the meanwhile... a difference can be that we use Cake to run the build. The command is:

    MSBuild(solutionFile, new MSBuildSettings {
        Verbosity = Verbosity.Minimal,
        Configuration = "Release"
    });

**Comment by MichaelSimons** [comment] 2019-04-03 15:14
Curious if you using a recent version of Cake which supports VS 2019?  It looks like support was added [here](https://github.com/cake-build/cake/commit/faf6b3974a2e6fed0b6d2350d8fd4f22679074ad).

**Comment by giusepanzuto** [comment] 2019-04-03 15:44
it seams that use the preview version

/Program86/Microsoft Visual Studio/2019/Preview/MSBuild/Current/Bin/MSBuild.exe

**Comment by MichaelSimons** [comment] 2019-04-03 15:46
Ah yes, I didn't notice that.  Seems like that is going to be an issue.  I would follow up with Cake on this.

**Comment by MichaelSimons** [comment] 2019-04-03 18:05
Closing since this appears to be an external issue (e.g. Cake).

**Closed by MichaelSimons** 2019-04-03 18:05 UTC
