### ISSUE TITLE
image created in windows server 2016 fails to start in a windows server 2019

### ISSUE THREAD

**Issue by sumantfordev** [microsoft/dotnet-framework-docker#350] opened 2019-06-11 12:36 UTC
i have created a docker image that hosts my web application, using base image aspnet:4.8 tag. The build machine is on windows server 2016 and my docker/kubernetes cluster  where the image is suppose to run is using windows server 2019 
As per the image website - https://hub.docker.com/_/microsoft-dotnet-framework-aspnet, it specfies that 4.8 tag image multi architecture, and my assumption was it should run, i am able to pull the image however it fails to start with error -The container operating system does not match the host operating system.
Please suggest.

**Comment by StephenMolloy** [comment] 2019-08-09 22:49
@sumantfordev is this still an issue for you?

**Comment by sumantfordev** [comment] 2019-08-15 14:53
I tried this  a month back and had the same issue . 
 
The issue seems to me relates to container layers on top of the base image. When you create a image in a windows 2016 server, then any command in the docker file is just a container layer on top if 4.8 2016 type image, but when you pull and start that container in a 2019 server, the base image pulled is 4.8 2019 type but since the command layers doesn't matches it fails to start.

If there is a new version of the image available let me know i can try this out .

**Comment by MichaelSimons** [comment] 2019-08-15 20:50
As noted, the .NET Framework repos publish multi-platform tags.  This means if you pull a multi-platform tag from a 2016 host you will get a 2016 based image.  If you pull the same tag from a 2019 host, you will get a 2019 based image.  If you build a single image based on a multi-platform tag, you do not get a multi-platform image rather you get a single image compatible with the host's platform.  

This seems somewhat orthogonal to your problem however.  If you want to produce an image that will work on a 2019 host, you will need to build the image on a 2019 or newer host.  This is because of the [Windows container compatibility limitations](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility).

Closing as this is the expected behavior.  Feel free however to continue the conversation.

**Closed by MichaelSimons** 2019-08-15 20:50 UTC
Labels: category:aspnet, question, triaged
