### ISSUE TITLE
Latest 4.7.2-windowsservercore-ltsc2019 image has an issue.

### ISSUE THREAD

**Issue by marat-turaev** [microsoft/dotnet-framework-docker#523] opened 2020-02-22 03:13 UTC
## Steps to reproduce the issue
1. On current image mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2019 (sha256:dbe184ba2656733b2879580950d36c20554ca68a473c384d4692ec75864a8cec) there is an issue with installing vcredist_x86.

2. Dockerfile:
FROM mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2019
ADD https://aka.ms/highdpimfc2013x86enu /vcredist_x86.exe
RUN C:\vcredist_x86.exe /quiet /install

## Expected behavior
Should be ok (and it is ok on a previous version: 4.7.2-20200114-windowsservercore-ltsc2019)

## Actual behavior
Fails with:
The command 'cmd /S /C C:\vcredist_x86.exe /quiet /install' returned a non-zero code: 3221225785

**Comment by kylecreekmore** [comment] 2020-02-22 07:03
I'm seeing a similar issue with the 4.8 version as well. Image with tag
`4.8-20200211-windowsservercore-ltsc2019` fails to run a simple .NET console application while using the previous tag `4.8-20191210-windowsservercore-ltsc2019` is fine.

**Comment by mthalman** [comment] 2020-02-24 14:07
I'm wondering whether you're running into this [1B host/2B container issue](https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t).  Can you compare the Windows version between your Docker container and your Docker host?  They should be the same in order for this to work because of this compatibility issue.  You can get the Windows version of the container by running this command:
```
docker pull mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
docker run --rm mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019 cmd /C ver
```
It should be `10.0.17763.1040`.  If you run the `ver` command on the Docker host, it should have the same version if the latest security updates are applied.

**Comment by vegasbrianc** [comment] 2020-02-25 16:03
We are also seeing this on all our 4.7.2 images since the Feb 19 release. It has broken all of our builds.

**Comment by mthalman** [comment] 2020-02-25 16:05
@vegasbrianc - Have you tried the resolution documented here: https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t?

**Comment by vegasbrianc** [comment] 2020-02-26 00:04
@mthalman Thanks for the link as this shines some light on why all of sudden working images stopped working. I am seeing several failures but we found older image tags to pin too. Unfortunately, this was an unexpected result as we thought we were pined to a stable version.

**Comment by jdebbink** [comment] 2020-02-26 15:24
We also had an issue with `mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019` from 2/19.

When our container starts the application pool is in a stopped state. Attempting to start it fails and the event log has this error:
```
A process serving application pool 'DefaultAppPool' terminated unexpectedly. The process id was '11864'. The process exit code was '0xc0000139'.
```

Looking up that exit code:
```
Error code 0xc0000139 is issued when windows is failing to load a dll file. The necessary dll files need to run your programm should be accessible by the OS. Put them either in the windows/system32 or in the folder where your exe is stored.
```

We updated our Dockerfile to base from `
`mcr.microsoft.com/dotnet/framework/aspnet:4.8-20200114-windowsservercore-ltsc2019` and that has gotten everything working as expected.

**Comment by jdebbink** [comment] 2020-02-26 15:46
@mthalman is there anything I can subscribe to so I can be notified of new issues relating to containers?

**Comment by mthalman** [comment] 2020-02-26 16:15
There's an [RSS feed](https://support.microsoft.com/en-us/help/4089498) for content that you could get for Windows but that's not specific to containers.  Your best option is to track things in this repo and we'll keep people informed of impactful issues as best we can.  This particular issue was tracked in our [release issue](https://github.com/microsoft/dotnet-framework-docker/issues/513) for this month's update.

**Comment by MichaelSimons** [comment] 2020-02-26 19:29
Closing as this is caused by the Windows container change that requires the Docker host machine match the container version.  See this [documentation](https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t) for additional details.

**Closed by MichaelSimons** 2020-02-26 19:29 UTC
