### ISSUE TITLE
Support generating WebDeploy packages

### ISSUE THREAD

**Issue by jmezach** [microsoft/dotnet-framework-docker#153] opened 2018-05-23 14:09 UTC
At the moment we are using [Octopus Deploy](https://octopus.com/) to deploy our application which consists of several ASP.NET WebAPI services as well as some background Windows Services. In order to package up our application for deployment with Octopus Deploy we are passing the DeployOnBuild property with a value of true to MSBuild, which then generates all the necessary files to run our application in obj\Release\Package\PackageTmp. We then package that up into a NuGet package and give that to Octopus Deploy.

Unfortunately it doesn't seem possible to have MSBuild generate these packages by using the container images provided here. Is this something that could be added? From what I understand #89 isn't enough to make this work.

**Comment by MichaelSimons** [comment] 2019-06-05 20:58
Resolving as duplicate of #157

**Closed by MichaelSimons** 2019-06-05 20:58 UTC
Labels: area:dockerfiles, area:external, duplicate, enhancement
